[package]
name = "oikade-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
oikade-config.workspace = true
oikade-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
